name: Run Python Tests on PRs
on:
  pull_request:
    branches: [ master ]
  push: # Adding push just for debbuging purposes ;)
    branches: [ master  ]
  workflow_dispatch: # Adding manual trigger just the same reason as the one mentioned above 


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run tests with pytest
      run: |
        pytest
